name: Artifact Uploading

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Test Report
        run: |
          echo "Test Report for Build" > report.txt
          echo "All tests passed!" >> report.txt

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.txt
