name: PR Events Demo

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  pr-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR Info
        run: |
          echo "Pull Request #${{ github.event.pull_request.number }} was ${{ github.event.action }} targeting branch ${{ github.base_ref }}"
