name: Secrets and Environment Variables

on:
  push:
    branches:
      - main

jobs:
  show-secrets:
    runs-on: ubuntu-latest
    steps:
      
      - name: Print Secret (Masked)
        run: echo "Using secret..."
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
